version: "3.9"

services:
  mlops-pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlops_pipeline
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=production
    restart: unless-stopped
